export const API_ROUTES = {
  auth: {
    login: '/auth/login',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    me: '/auth/me',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    verifyEmail: '/auth/verify-email',
  },
  tenant: {
    current: '/tenant/settings',
    updateSettings: '/tenant/settings',
  },
  outlets: {
    list: '/outlets',
    detail: (id: string) => `/outlets/${id}`,
  },
  appointments: {
    list: '/appointments',
    create: '/appointments',
    detail: (id: string) => `/appointments/${id}`,
    update: (id: string) => `/appointments/${id}`,
    cancel: (id: string) => `/appointments/${id}/cancel`,
    reschedule: (id: string) => `/appointments/${id}/reschedule`,
    slots: '/appointments/slots',
  },
  services: {
    list: '/services',
    create: '/services',
    categories: '/services/categories',
    detail: (id: string) => `/services/${id}`,
    update: (id: string) => `/services/${id}`,
    delete: (id: string) => `/services/${id}`,
  },
  staff: {
    list: '/staff',
    create: '/staff',
    detail: (id: string) => `/staff/${id}`,
    update: (id: string) => `/staff/${id}`,
    delete: (id: string) => `/staff/${id}`,
    leaves: {
      list: '/staff/leaves',
      create: '/staff/leaves',
      delete: (id: string) => `/staff/leaves/${id}`,
    },
    breaks: {
      list: '/staff/breaks',
      create: '/staff/breaks',
      delete: (id: string) => `/staff/breaks/${id}`,
    },
    schedule: {
      get: (staffId: string) => `/staff/${staffId}/schedules`,
      update: (staffId: string) => `/staff/${staffId}/schedules`,
    },
  },
  customers: {
    list: '/customers',
    create: '/customers',
    detail: (id: string) => `/customers/${id}`,
    update: (id: string) => `/customers/${id}`,
    delete: (id: string) => `/customers/${id}`,
    notes: {
      create: (customerId: string) => `/customers/${customerId}/notes`,
      list: (customerId: string) => `/customers/${customerId}/notes`,
      delete: (customerId: string, noteId: string) => `/customers/${customerId}/notes/${noteId}`,
    },
  },
  billing: {
    invoices: '/billing/invoices',
    createInvoice: '/billing/invoices',
    invoiceDetail: (id: string) => `/billing/invoices/${id}`,
    recordPayment: (invoiceId: string) => `/billing/invoices/${invoiceId}/payments`,
    cancelInvoice: (invoiceId: string) => `/billing/invoices/${invoiceId}/cancel`,
  },
  reports: {
    summary: '/reports/summary',
    revenue: '/reports/revenue',
    staff: '/reports/staff',
    services: '/reports/services',
    customers: '/reports/customers',
  },
  roles: {
    list: '/roles',
    create: '/roles',
    permissions: '/roles/permissions',
    detail: (id: string) => `/roles/${id}`,
    update: (id: string) => `/roles/${id}`,
    delete: (id: string) => `/roles/${id}`,
  },
};
